config/routes.rb
Rails.application.routes.draw do

  namespace :api, defaults: { format: :json } do
    match '/events', to: 'events#index', via: [:options]
    resources :events, only: [:create]
  end

  resources :sessions, only: [:new, :create, :destroy]
  resources :users, only: [:new, :create]
  resources :password_resets, param: :token, except: :destroy
  resources :registered_applications
  root "registered_applications#index"

  get "sign_up" => "users#new", :as => "sign_up"

  get "sign_in" => "sessions#new", :as => "sign_in"
  get "sign_out" => "sessions#destroy", :as => "sign_out"  

  get 'confirmations/:id' => "confirmations#update", as: "confirmation"

end

app/models/event.rb
class Event < ActiveRecord::Base
  belongs_to :registered_application
end

app/models/registered_application.rb
class RegisteredApplication < ActiveRecord::Base
  validates_uniqueness_of :URL, :name
  validates_presence_of :URL, :name
  
  belongs_to :user
  has_many :events, dependent: :destroy
end

app/models/user.rb
class User < ActiveRecord::Base
  attr_accessor :password
  before_save :encrypt_password
  has_many :registered_applications, dependent: :destroy

  validates_confirmation_of :password
  validates_presence_of :password, :on => :create
  validates_format_of :email, :with => /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\Z/i, :on => :create
  validates_presence_of :email
  validates_uniqueness_of :email

  def send_password_reset
    generate_token(:password_reset_token)
    self.password_reset_sent_at = Time.zone.now
    save!
    UserMailer.password_reset(self).deliver_now
  end

  def generate_token(column)
    begin
      token = SecureRandom.urlsafe_base64
      self[column] = token
    end while User.exists?(column => token)
  end

  def self.authenticate(email, password)
    user = find_by_email(email)
    if user && user.password_hash == BCrypt::Engine.hash_secret(password,user.password_salt)
      user
    else
      nil
    end   
  end
  def encrypt_password
    if password.present?
      self.password_salt = BCrypt::Engine.generate_salt
      self.password_hash = BCrypt::Engine.hash_secret(password,password_salt)
    end
  end

  def confirmed?
    self.confirm
  end

end

app/controllers/api/events_controller.rb
class Api::EventsController < ApplicationController
  #how to do in production?
  skip_before_action :verify_authenticity_token
  before_filter :set_access_control_headers

  def set_access_control_headers
    headers['Access_Control-Allow-Origin'] = '*'
    headers['Access-Control-Allow-Methods'] = 'Post, GET, OPTIONS'
    headers['Access-Control-Allow-Headers'] = 'Content-Type'
  end

  def create
    app = RegisteredApplication.find_by(url: request.env['HTTP_ORIGIN'])
    if app 
      @event = app.events.create(event_params)
      if @event.persisted?
        #checking if @event has an id
        render json: @event, status: :created
      else
        render @event.errors, status: :unprocessable_entity
      end
    else
      render json: "Unregistered application", status: :unprocessable_entity
    end
  end

  private
  def event_params
    params.require(:event).permit(:name)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  helper_method :current_user

  private
  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end
end

app/controllers/confirmations_controller.rb
class ConfirmationsController < ApplicationController

  def update
    @user = User.find(params[:id])
    @user.confirm = true
    if @user.save
      flash[:notice] = "Thank you for confirming your account!"
      redirect_to root_url
    else
      flash[:error] = "Failed to confirm account"
      render :edit
    end
  end
end

app/controllers/password_resets_controller.rb
class PasswordResetsController < ApplicationController
  def new
  end
  def create
    user = User.find_by_email(params[:email])
    if user
      user.send_password_reset 
      redirect_to root_url, notice: "Email sent with password reset instructions."
    else
      redirect_to new_password_reset_path, alert: "We couldn't find this user."
    end
  end

  def edit
    @user = User.find_by_password_reset_token!(params[:token])
  end

  def update
    @user = User.find_by_password_reset_token!(params[:token])
    if @user.password_reset_sent_at < 2.hours.ago
      redirect_to new_password_reset_path, alert: "Password reset has expired, please reset again."
    elsif @user.update_attributes(user_params)
      redirect_to root_url, notice: "password reset successful!"
    else
      render :edit, error: 'failed to update password'
    end
  end

  private
  def user_params
    params.require(:user).permit(:password, :password_confirmation)
  end
end

app/controllers/registered_applications_controller.rb
class RegisteredApplicationsController < ApplicationController
  def index
    if current_user
      @apps = current_user.registered_applications
    else
      redirect_to sign_in_path
    end
  end

  def new
    @app = RegisteredApplication.new
  end
  
  def create
    @app = RegisteredApplication.new(app_params)
    @app.user = current_user
    if @app.save
      redirect_to registered_applications_path, notice: "successfully linked new application"
    else
      render :new, alert: "Failed to link application"
    end
  end
  
  def show
    set_app
    @events = @app.events    
  end

  def edit
    set_app
    if !@app 
      redirect_to registered_applications_path, warning: "you are not authorized to read"
    end
  end

  def update
    set_app
    if @app.update_attributes(app_params) 
      redirect_to registered_applications_path, notice: "successfully updated application details"  
    else
      render :edit, error: "something went wrong in updating the application"
    end
  end

  def destroy
    set_app
    if @app.destroy
      redirect_to registered_applications_path, notice: "succesfully deleted application"
    else
      redirect_to registered_applications_path, error: "something went wrong in deleting this application"
    end
  end

  private
  def set_app
    @app = current_user.registered_applications.find(params[:id])
  end
  def app_params
    params.require(:registered_application).permit(:name, :URL)
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    user = User.authenticate(params[:email], params[:password])
    if user && user.confirmed?
      session[:user_id] = user.id
      redirect_to registered_applications_path, :notice => "logged in"
    elsif user && !user.confirmed?
      flash[:alert] = "please check your email to complete sign up process"
      redirect_to sign_in_path
    else
      flash[:alert] = "invalid log in credentials"
      render "new"      
    end

  end

  def destroy
    session[:user_id] = nil
    redirect_to root_url, :notice => "successfully logged out"
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      UserMailer.send_signup_email(@user).deliver_now
      redirect_to root_url, notice: "please check your email to confirm your account"
    else
      render "new"
    end
  end

  private
  def user_params
    params.require(:user).permit(:email, :password, :password_confirmation)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  ALERT_TRANSLATION = {notice: 'info', error: 'danger', alert: 'warning'}.with_indifferent_access
  
  def alert_class(name)
    ALERT_TRANSLATION[name]
  end
end

app/helpers/events_helper.rb
module EventsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Blocmetrics</title>
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag "//www.google.com/jsapi", "chartkick" %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <div class="container">
    <ul class="nav nav-tabs">
      <div class="pull-right user-info">
        <% if current_user %>
          Logged in as <%= current_user.email %>
          <%= link_to "Log out", sign_out_path %>
        <% else %>
          <%= link_to "Log in", sign_in_path %> | 
          <%= link_to "Sign up", sign_up_path %>
        <% end %>
      </div>
    </ul>
    <% flash.each do |name, msg| %>
      <div class="alert alert-<%= alert_class(name)%>">
        <%= content_tag :div, msg %>
      </div>
    <% end %>
    <%= yield %>

  </div>


</body>
</html>

app/views/password_resets/edit.html.erb
<h1>Reset your password</h1>
<%= form_for @user, url: password_reset_path(params[:token]) do |f| %>
  <% if @user.errors.any? %>
    <div class="error_msg">
      <ul>
        <% @user.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :password %>
    <%= f.password_field :password %>
  </div>
  <div class="field">
    <%= f.label :password_confirmation %>
    <%= f.password_field :password_confirmation %>
  </div>
  <div class="actions"><%= f.submit "Update Password"%></div>
<% end %>

app/views/password_resets/new.html.erb
<h1>Reset Password</h1>

<%= form_tag password_resets_path, method: :post do %>
  <div class="field">
    <%= label_tag :email %>
    <%= text_field_tag :email, params[:email] %>
  </div>
  <%= submit_tag "Reset Password" %>
<% end %>

app/views/registered_applications/_form.html.erb
<%= form_for @app do |f| %>
 <% if @app.errors.any? %> 
    <div class="error_messages">
      <h2>Form is invalid</h2>
      <ul>
        <% for msg in @app.errors.full_messages %>
          <li><%=msg %></li>
        <% end %>
      </ul>  
    </div>
  <% end %>
  <p>
    <%= f.label :name %></br>
    <%= f.text_field :name %>
  </p>
  <p>
    <%= f.label :URL %></br>
    <%= f.text_field :URL %>
  </p>
 
  <%= f.submit %>
<% end %>

app/views/registered_applications/edit.html.erb
<h1>Edit application</h1>
<%= render 'form' %>

app/views/registered_applications/index.html.erb
<h1>My registered applications</h1>
<%= link_to "Create new", new_registered_application_path %>
<div>
<% @apps.each do |a| %>
  <p>
  <%= link_to a.name, registered_application_path(a) %>
  </p>
<% end %>
</div>

app/views/registered_applications/new.html.erb
<h1>Register a new application</h1>
<%= render 'form' %>

app/views/registered_applications/show.html.erb
<h1>Application Details</h1>

<div>

  <%=@app.name %>
  <p><%= @app.URL %></p>
  <%= link_to "edit", edit_registered_application_path(@app) %></br>
  <%= link_to "delete app", registered_application_path(@app), method: :delete %>
  <h3>Events logged</h3>
  <%= pie_chart @events.group(:name).count %>
  <%#= line_chart @events.group_by_day(:created_at).count %>
</div>

app/views/users/new.html.erb
<h1>Sign up</h1>

<%= form_for @user do |f| %>
  <% if @user.errors.any? %> 
    <div class="error_messages">
      <h2>Form is invalid</h2>
      <ul>
        <% for msg in @user.errors.full_messages %>
          <li><%=msg %></li>
        <% end %>
      </ul>  
    </div>
  <% end %>
  <p>
    <%= f.label :email %></br>
    <%= f.text_field :email %>
  </p>
  <p>
    <%= f.label :password %></br>
    <%= f.password_field :password %>
  </p>
  <p>
    <%= f.label :password_confirmation %></br>
    <%= f.password_field :password_confirmation %>
  </p>

  <%= f.submit %>
<% end %>